# Generated by Django 5.1.6 on 2025-06-14 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_debt_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='debts', related_query_name='debt', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
