# Generated by Django 5.1.6 on 2025-06-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_alter_debt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='status',
        ),
    ]
