# Generated by Django 5.1.6 on 2025-06-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_remove_debt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Dívida'),
        ),
    ]
