# Generated by Django 5.1.6 on 2025-06-15 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_alter_debt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10, validators=[django.core.validators.MaxValueValidator(99999999.99), django.core.validators.MinValueValidator(0.01)], verbose_name='Valor da Dívida'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='installments',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(420)], verbose_name='Parcelas'),
        ),
    ]
