# Generated by Django 5.1.6 on 2025-06-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0008_alter_debt_financier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': 'Dívida', 'verbose_name_plural': 'Dívidas'},
        ),
    ]
