# Generated by Django 5.1.6 on 2025-08-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0009_alter_debt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='category',
            field=models.IntegerField(choices=[(3, 'Cartão de Crédito'), (4, 'Financiamento'), (5, 'Empréstimo'), (6, 'Cheque Especial'), (7, 'Outros')], verbose_name='Categoria'),
        ),
    ]
