# Generated by Django 5.1.6 on 2025-03-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0002_debit_is_paid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debit',
            new_name='Debt',
        ),
    ]
