# Generated by Django 5.1.6 on 2025-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor')),
                ('category', models.IntegerField(choices=[(3, 'Vestuário'), (4, 'Dívidas'), (5, 'Educação'), (6, 'Alimentação'), (7, 'Presentes'), (8, 'Saúde'), (9, 'Moradia'), (10, 'Investimentos'), (11, 'Lazer'), (12, 'Pets'), (13, 'Tecnologia'), (14, 'Transporte'), (15, 'Outros')], verbose_name='Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transação')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('destination', models.CharField(max_length=55, verbose_name='Destino')),
                ('is_paid', models.BooleanField(verbose_name='Pago?')),
                ('transaction_type', models.IntegerField(choices=[(1, 'Saída'), (2, 'Entrada')], verbose_name='Tipo de entrada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
            ],
        ),
    ]
