# Generated by Django 5.1.6 on 2025-04-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor')),
                ('category', models.IntegerField(choices=[(1, 'Vestuário'), (2, 'Dívidas'), (3, 'Educação'), (4, 'Alimentação'), (5, 'Presentes'), (6, 'Saúde'), (7, 'Moradia'), (8, 'Investimentos'), (9, 'Lazer'), (10, 'Pets'), (11, 'Tecnologia'), (12, 'Transporte'), (13, 'Outros')], verbose_name='Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('destination', models.CharField(max_length=55, verbose_name='Destino')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Pago?')),
                ('transaction_type', models.IntegerField(choices=[(1, 'Saída'), (2, 'Entrada')], verbose_name='Tipo de entrada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
            ],
        ),
    ]
