# Generated by Django 5.1.6 on 2025-04-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Saída'), (2, 'Entrada')], verbose_name='Tipo'),
        ),
    ]
