# Generated by Django 5.1.6 on 2025-10-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default='2025-10-19', verbose_name='Data'),
            preserve_default=False,
        ),
    ]
