# Generated by Django 5.1.6 on 2025-04-14 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Já existe um usuário com esse CPF.'}, max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, message='O CPF precisa ter 11 caracteres.')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Já existe um usuário com esse e-mail.'}, max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
