# Generated by Django 5.1.6 on 2025-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('name', models.CharField(max_length=55, verbose_name='Nome')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
        ),
    ]
